compact: true
directory: aws-databricks
download-external-modules: true
evaluate-variables: true
external-modules-download-path: .external_modules
quiet: true
skip-path:
  - .external_modules
  - modules
