name: "Terratest GitHub Action"
on:
  pull_request:
    branches: [test, dev, qa, prod, main]
  push:
    branches: [test, dev, qa, prod, main]
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.TERRATEST_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_KEY: ${{ secrets.TERRATEST_AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.TERRATEST_AWS_REGION }}
  AWS_REGION: ${{ secrets.TERRATEST_AWS_REGION }}
  TF_VAR_databricks_account_username: ${{ secrets.DATABRICKS_ACCOUNT_USERNAME }}
  TF_VAR_databricks_account_password: ${{ secrets.DATABRICKS_ACCOUNT_PASSWORD }}
  TF_VAR_databricks_account_id: ${{ secrets.DATABRICKS_ACCOUNT_ID }}
jobs:
  terratest:
    name: terratest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Go (1.16)
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go
      - name: Run 'go test -v -timeout 30m'
        run: |
          cd test
          go mod download
          go test -v -timeout 30m
